# https://lychee.cli.rs/usage/config/
scheme = ["https", "http"]
exclude = [
  '^https://portal.azure.com/',
  '^https://gitlab.com/profile/personal_access_tokens',
  '^https://my.bitbucketserver.com/path/to/pipeline/repo',
  '^https://github.com/organizations/',
  '^https://github.com/pipeline-repo',
  '^https://api.tower.nf/ephemeral/example.json',
  '^https://api.cloud.seqera.io/workflow/launch'
]
